# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More

# Sidebar
sidebar: right
widgets:
- about
- recent_posts
- tagcloud
- archive
- gh_commits

# Miscelaneous
favicon: /favicon.png
